/*
 *
 * ComicsListPage constants
 *
 */

export const FETCH_COMICS_LIST = 'app/ComicsListPage/FETCH_COMICS_LIST'
export const FETCH_COMICS_LIST_SUCCESS = 'app/ComicsListPage/FETCH_COMICS_LIST_SUCCESS'
export const FETCH_COMICS_LIST_FAILURE = 'app/ComicsListPage/FETCH_COMICS_LIST_FAILURE'
export const FETCH_CHARACTERS_FOR_SEARCH = 'app/ComicsListPage/FETCH_CHARACTERS_FOR_SEARCH'
export const FETCH_CHARACTERS_FOR_SEARCH_FINISHED = 'app/ComicsListPage/FETCH_CHARACTERS_FOR_SEARCH_FINISHED'
